apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: heartdiseaseprediction
  description: A machine learning application designed to predict the likelihood of heart disease based on various health metrics.
  annotations:
    github.com/project-slug: Musquan/HeartDiseasePrediction
    jira/project-key: SCRUM
    jira/label: backstage-component:heartdiseaseprediction
spec:
  type: application
  owner: ICS
  lifecycle: experimental